/// Auto-generated by dioxus-iconify - DO NOT EDIT
/// Generated: 2026-04-21T04:08:47.060099447+00:00
/// Collection: mdi
/// This is a partial import from Iconify
/// Browse icons: <https://icon-sets.iconify.design/mdi/>
///
/// ```yaml
/// name: Material Design Icons
/// author:
///   name: Pictogrammers
///   url: https://github.com/Templarian/MaterialDesign
/// license:
///   title: Apache 2.0
///   spdx: Apache-2.0
///   url: https://github.com/Templarian/MaterialDesign/blob/master/LICENSE
/// total: 7447
/// category: Material
/// palette: false
/// height: 24
/// ```
use super::IconData;

#[allow(non_upper_case_globals)]
pub const Home: IconData = IconData {
    name: "mdi:home",
    body: r#"<path fill="currentColor" d="M10 20v-6h4v6h5v-8h3L12 3L2 12h3v8z"/>"#,
    view_box: "0 0 24 24",
    width: "24",
    height: "24",
};
